### ISSUE TITLE
dist build seems to contain React

### ISSUE THREAD

**Issue by bebraw** [NickTomlin/react-table#2]
That might be something you want to avoid. Just thought to point this out as it's preferable to load whatever version of React people like to use.

**Comment by NickTomlin** [comment]
@bebraw 

You make an excellent point; most people that are consuming dist are probably going to have react on the window anyway. I'll get a fix out for this soon.

**Comment by NickTomlin** [comment]
@bebraw

Just pushed a fix. Feel free to kick the tires, and thanks for the feedback!
