### ISSUE TITLE
Set default column to sort by

### ISSUE THREAD

**Issue by dsernst** [NickTomlin/react-table#4]
It would be great if you could pass in a prop to `<ReactTable>` to set a default column to sort by, and direction.

**Comment by NickTomlin** [comment]
Good call, I'll add this to the list.

**Comment by dsernst** [comment]
I'm happy to work on it and send a PR if you can suggest a strategy.

**Comment by NickTomlin** [comment]
@dsernst sorry for the late reply!

I fee like the code could used cleaning up, but we could potentially add another else block to [this](https://github.com/NickTomlin/react-table/blob/master/src/table.js#L99) logic here that uses props.sortKey before falling back to the first row. That's just my opinion though, so if you think of a better way let's go for it!

**Comment by NickTomlin** [comment]
@dsernst I took an initial [stab](https://github.com/NickTomlin/react-table/commit/48790ee7b5acee044e6163f6f33043b3bedb9a9d) at it. Would love to hear your thoughts.

**Comment by dsernst** [comment]
Looks and works great!

**Comment by dsernst** [comment]
Do you think a similar thing would be easy for `initialDirection`? It's not as necessary because I was able to go in and manually adjust the `getInitialState` for the constructor. 

In any case this one works great, thanks for the great job.
