### ISSUE TITLE
Add instructions to help develop

### ISSUE THREAD

**Issue by dsernst** [NickTomlin/react-table#5]
In #4 you linked to a new branch with the `initialSortKey` feature and invited me to try it out. Thanks! That was great.

I ran into a little trouble with getting this new code into my existing project (where I had previously just done `npm install react-table`). 

Here's what I did to make it work for now:

1. fork this repo on GitHub
2. clone my fork locally to `/Users/dsernst/Documents/react-table/`
3. from my fork: `git checkout origin/#4-configurable-sort-column`
4. from this detached HEAD, checkout into a new local branch: `git checkout -b \#4-configurable-sort-column`
5. `npm pack` to make it into a local tarball
6. Went back to my project that uses `react-table` and then: `npm install /Users/dsernst/Documents/react-table/react-table-1.3.0.tgz`

I don't know if this is how you're managing local development, but whatever it is, it might be helpful to add some instructions to the README to lower the barrier to entry.

In any case, thanks again for being so responsive with #4.

**Comment by dsernst** [comment]
Oh looks like [`npm link`](https://docs.npmjs.com/cli/link) could be used to replace steps 5 & 6, and in a cleaner way for future changes.

**Comment by NickTomlin** [comment]
Great suggestion! I think what this project needs is a [CONTRIBUTING](https://github.com/blog/1184-contributing-guidelines) file. We can include some ways to get up and running as well as any guidelines. Do you want to start a branch with a basic CONTRIBUTING file that contains your instructions (with npm link and also pointing to my suggestion below if works well for you). We can work on it together and get into the project.

`npm link` is a great way to do things, you can also to a [git url](https://docs.npmjs.com/files/package.json#git-urls-as-dependencies) in your project's package.json e.g. 

```
dependencies: {
  "react-table": "nicktomlin/react-table#4-configurable-sort-column"
}
```

Although that it wouldn't allow you to run against local changes.
